### ISSUE TITLE
"slice bounds out of range" error when passing some urls

### ISSUE THREAD

**Issue by SkobelkinYaroslav** [riza/indextree#1]
i get an error when i pass url "https://www.youtube.com/"

to fix it implement a length check of s.Text() in "parseIndex" function before if s.Text()[len(s.Text())-1:] != "/" {...}

![image](https://github.com/riza/indextree/assets/120472314/6497c15d-7eca-410d-816b-d51ae50c839a)

**Comment by riza** [comment]
Hello @SkobelkinYaroslav,

indextree is not exactly a tool that crawls URLs on a website,

Indextree is a tool developed to crawl the directory listing pages of web servers as I exemplify below.

I will update the README to be more understandable, thanks for the issue.

Best regards,
Riza

Example: 

![image](https://github.com/riza/indextree/assets/2565849/b664657e-316c-4418-a1a4-edece3a601a9)
